services:

  bff:
    build:
      context: .  # Текущая папка с BFF
      dockerfile: Dockerfile
    container_name: bff-service
    restart: on-failure
    environment:
      # Базовые URL сервисов
      SVC_USER_BASE_URL: http://userservice:8080
      SVC_COMPETITION_BASE_URL: http://competitionservice:8080
      SVC_FEEDBACK_BASE_URL: http://feedbackservice:8080
      SVC_ENGINE_BASE_URL: http://engineservice:8080
      SVC_CHAT_BASE_URL: http://chatservice:8000
      SVC_STATISTIC_BASE_URL: http://statisticservice:8080
      # Настройки Spring Boot
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  microservices-net:
    external: true